source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/plugins/plugins.vim
source $HOME/.config/nvim/plugins/lspconfig/lspconfig.vim
source $HOME/.config/nvim/plugins/fern/fern.vim
luafile $HOME/.config/nvim/plugins/compe/compe.lua
luafile $HOME/.config/nvim/plugins/language_servers/language_servers.lua
source $HOME/.config/nvim/general/startup.vim
source $HOME/.config/nvim/plugins/airline/airline.vim
